In [1]:
import numpy as np

def rel_error(x, y):
  """ returns relative error """
  return np.max(np.abs(x - y) / (np.maximum(1e-8, np.abs(x) + np.abs(y))))

In [4]:
x = [1, -2, 3]
y = [2, 4, -6]
np.abs(y)

array([2, 4, 6])

In [5]:
np.abs(x) + np.abs(y)

array([3, 6, 9])

In [6]:
1e-8

1e-08

In [7]:
np.maximum(1e-8, np.abs(x) + np.abs(y))

array([3., 6., 9.])

In [8]:
np.maximum(1e-8, [0,0,0])

array([1.e-08, 1.e-08, 1.e-08])

In [9]:
np.abs(x - y)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [10]:
rel_error(x, y)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [18]:
rel_error(5, 60)

0.8461538461538461

In [24]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)
2 * np.prod((1, 5, 6))

60

In [34]:
x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

print(x.shape)
print(w.shape)
print(b.shape)

print(x[0][0])

(2, 4, 5, 6)
(120, 3)
(3,)
[[-0.1        -0.09748954 -0.09497908 -0.09246862 -0.08995816 -0.0874477 ]
 [-0.08493724 -0.08242678 -0.07991632 -0.07740586 -0.0748954  -0.07238494]
 [-0.06987448 -0.06736402 -0.06485356 -0.0623431  -0.05983264 -0.05732218]
 [-0.05481172 -0.05230126 -0.04979079 -0.04728033 -0.04476987 -0.04225941]
 [-0.03974895 -0.03723849 -0.03472803 -0.03221757 -0.02970711 -0.02719665]]


In [46]:
""" forward pass """
x_reshaped = x.reshape(x.shape[0], -1)
print('x_reshaped shape: ', str(x_reshaped.shape))
out = x_reshaped.dot(w)
out.shape
print(out)
out = out + b
print('bias: ', b)
out

x_reshaped shape:  (2, 120)
[[1.79834967 1.80660132 1.81485297]
 [3.55553199 3.6141327  3.67273342]]
bias:  [-0.3 -0.1  0.1]


array([[1.49834967, 1.70660132, 1.91485297],
       [3.25553199, 3.5141327 , 3.77273342]])

In [47]:
# Test the affine_backward function
np.random.seed(231)
x = np.random.randn(10, 2, 3)
w = np.random.randn(6, 5)
b = np.random.randn(5)
dout = np.random.randn(10, 5)

In [51]:
dout

array([[-1.80480094,  0.53770564, -0.12171369, -1.04250949,  0.13828792],
       [-0.22557183, -1.1928829 , -0.68320696,  0.19909408,  0.03070661],
       [-0.44972639,  0.14447532, -0.35229594,  0.4882136 , -0.4347099 ],
       [-0.28692265, -0.84338097, -0.10827394,  0.85434757, -0.90377338],
       [-1.0525584 , -0.30409794,  0.18083726, -0.4125417 ,  1.22913948],
       [-0.97791748, -0.63978524, -0.00880963,  0.36213294,  0.35148162],
       [-1.20064035, -0.84272962,  1.61832501, -2.39079478,  0.88256212],
       [-1.12082008,  0.12416778, -2.43434598, -1.62701704, -1.10613945],
       [ 2.00862337,  0.91447992, -0.86943856,  0.13741017, -0.72261465],
       [-0.6755518 , -0.04084145, -1.15755894, -0.67498124,  0.44252644]])

In [54]:
from cs231n.gradient_check import eval_numerical_gradient, eval_numerical_gradient_array

# dx_num = eval_numerical_gradient_array(lambda x: affine_forward(x, w, b)[0], x, dout)
# dw_num = eval_numerical_gradient_array(lambda w: affine_forward(x, w, b)[0], w, dout)
# db_num = eval_numerical_gradient_array(lambda b: affine_forward(x, w, b)[0], b, dout)
# dx_num

In [56]:
x = np.linspace(-0.5, 0.5, num=12).reshape(3, 4)
x

array([[-0.5       , -0.40909091, -0.31818182, -0.22727273],
       [-0.13636364, -0.04545455,  0.04545455,  0.13636364],
       [ 0.22727273,  0.31818182,  0.40909091,  0.5       ]])

In [65]:
0.001 * np.random.randn(3, 5)

array([[ 0.00078546,  0.00052003, -0.00047831, -0.00020406, -0.00095556],
       [-0.00168961,  0.00037476,  0.00082023, -0.00185008,  0.00082419],
       [-0.00128956, -0.00150315, -0.00136003,  0.00134741,  0.0007343 ]])

In [67]:
np.random.randint(50, size=3)

array([18, 46, 42])

In [88]:
# testing softmax
np.random.seed(231)
num_classes, num_inputs = 2, 5
x = 0.001 * np.random.randn(num_inputs, num_classes)
y = np.random.randint(num_classes, size=num_inputs)

print(x)
print(y)

[[ 4.17943411e-04  1.39710028e-03]
 [-1.78590431e-03 -7.08827734e-04]
 [-7.47253161e-05 -7.75016769e-04]
 [-1.49797903e-04  1.86172902e-03]
 [-1.42552930e-03 -3.76356699e-04]]
[0 0 0 1 0]


In [90]:
# calculating softmax
shifted_logits = x - np.max(x, axis=1, keepdims=True)
x - np.max(x, axis=1, keepdims=True)

array([[-0.00097916,  0.        ],
       [-0.00107708,  0.        ],
       [ 0.        , -0.00070029],
       [-0.00201153,  0.        ],
       [-0.00104917,  0.        ]])

In [112]:
Z = np.sum(np.exp(shifted_logits), axis=1, keepdims=True)
print(np.exp(shifted_logits))
np.sum(np.exp(shifted_logits), axis=1, keepdims=True)

[[0.99902132 1.        ]
 [0.9989235  1.        ]
 [1.         0.99929995]
 [0.99799049 1.        ]
 [0.99895138 1.        ]]


array([[1.99902132],
       [1.9989235 ],
       [1.99929995],
       [1.99799049],
       [1.99895138]])

In [114]:
print(np.log(Z))
log_probs = shifted_logits - np.log(Z)
print(log_probs)

[[0.69265772]
 [0.69260879]
 [0.6927971 ]
 [0.69214192]
 [0.69262273]]
[[-0.69363688 -0.69265772]
 [-0.69368586 -0.69260879]
 [-0.6927971  -0.69349739]
 [-0.69415345 -0.69214192]
 [-0.6936719  -0.69262273]]


In [115]:
probs = np.exp(log_probs)
print(probs)

[[0.49975521 0.50024479]
 [0.49973073 0.50026927]
 [0.50017507 0.49982493]
 [0.49949712 0.50050288]
 [0.49973771 0.50026229]]


In [118]:
N = x.shape[0]
loss = -np.sum(log_probs[np.arange(N), y]) / N
dx = probs.copy()
dx[np.arange(N), y] -= 1
dx /= N
log_probs[np.arange(N), y]

array([-0.69363688, -0.69368586, -0.6927971 , -0.69214192, -0.6936719 ])

In [148]:
# testing weight initialization with Gaussian distribution
np.random.seed(231)
N = 5
weight_scale = 0.0001
x = np.random.randn(5)
x1 = x / np.mean(x, axis = 0)
x1 = x1 * np.sqrt(weight_scale)
print(x)
print(x / np.sqrt(N))
print(x1)
print(abs(x.std() - weight_scale))
print(abs(x1.std() - weight_scale))

[ 0.41794341  1.39710028 -1.78590431 -0.70882773 -0.07472532]
[ 0.18690998  0.62480224 -0.79868069 -0.3169974  -0.03341818]
[-0.02769988 -0.09259511  0.11836373  0.04697872  0.00495254]
1.0685639056136496
0.07072744849644229
